NH-66480: remove packagecloud and downgrade graphql version
solarwinds/solarwinds-apm-ruby pull request #48
Opened 2024-01-17 14:15 UTC by xuan-cao-swi

2024-01-18 16:42 UTC, xuan-cao-swi commented
Won't fix https://github.com/solarwinds/solarwinds-apm-ruby/security/code-scanning/3 since can't find better way to sanitize graphql. P.S. current otel graphql instrumentation doesn't have sanitization.

2024-01-18 19:46 UTC, cheempz reviewed
Thanks @xuan-cao-swi! Question about the graphql handling and as discussed will wait for your fix on the failing tests.

2024-01-18 19:46 UTC, cheempz commented on lib/solarwinds_apm/inst/graphql.rb
> +          raise ArgumentError, "Query is too long for sanitize." if query.length > MAX_QUERY_LENGTH
Is this exception caught by our instrumentation higher up the stack (and handled by logging a warning message)?  We should never cause an unhandled exception in the customer's application.

Also, we should return an empty query string if it's too long to sanitize, instead of just an unsanitized version.

2024-01-18 19:58 UTC, xuan-cao-swi commented on lib/solarwinds_apm/inst/graphql.rb
> +          raise ArgumentError, "Query is too long for sanitize." if query.length > MAX_QUERY_LENGTH
Ah, yeah, should return empty instead of raising error. Updated

2024-01-20 00:04 UTC, cheempz commented on test/unit/oboe_init_options_test.rb
> +    _(options[20]).must_equal 2
There is no test to confirm an appoptics collector endpoint results in metrics mode of 1 now. This test needs to be fixed to actually "checks for metric mode appoptics".

2024-01-20 00:06 UTC, cheempz requested changes
Looks good @xuan-cao-swi, just need that metrics mode for AO test fixed.

2024-01-22 16:20 UTC, xuan-cao-swi commented on test/unit/oboe_init_options_test.rb
> +    _(options[20]).must_equal 2
Fixed

2024-01-22 18:37 UTC, cheempz approved these changes
Thanks for the enhanced tests @xuan-cao-swi!

2024-01-22 19:44 UTC, merged